rule:
  - column: Customer_Age
    range: [25, 65]
  - column: Education_Level
    string_length: [0, 10]
  - column: Total_Relationship_Count
    range: [2, 4]
  - column: Credit_Limit
    range: [3500, 9500]
  - column: Total_Revolving_Bal
    range: [100, 1000]
